package com.vayurakshak.airquality.alert.dto;

import com.vayurakshak.airquality.alert.entity.AlertSeverity;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Getter;

@Getter
@Builder
@Schema(description = "Alert generated by smart monitoring system")
public class AlertResponse {

    @Schema(example = "High Pollution Warning")
    private String title;

    @Schema(example = "AQI is in severe range. Avoid outdoor activity.")
    private String message;

    private AlertSeverity severity;
}
